const LOGO_URL="https://i.ibb.co/rRqtGKkw/0db84367-e795-4617-835e-5e0a2bf2ff45.jpg";
const PAYMENT_METHODS=["instapay","vodafone_cash","telda"];
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...headers}});
const hash=async value=>{const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(n=>n.toString(16).padStart(2,"0")).join("")};
const clean=s=>String(s??"").trim();
const slugify=s=>clean(s).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||`item-${Date.now()}`;
const cookie=(value,maxAge)=>`kardivo_session=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;
const money=n=>Math.round(Number(n||0)*100)/100;
async function currentUser(req,env){const raw=req.headers.get("Cookie")||"",match=raw.match(/(?:^|; )kardivo_session=([^;]+)/);if(!match)return null;return env.DB.prepare("SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>? ").bind(match[1],Date.now()).first()}
async function ensureAdmin(env){if(!env.ADMIN_EMAIL||!env.ADMIN_PASSWORD)return;const email=clean(env.ADMIN_EMAIL).toLowerCase();const exists=await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first();if(!exists)await env.DB.prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,'admin')").bind("Kardivo Admin",email,await hash(env.ADMIN_PASSWORD)).run()}
async function settings(env){const rows=(await env.DB.prepare("SELECT key,value FROM settings").all()).results;return Object.fromEntries(rows.map(r=>[r.key,r.value]))}
async function productList(env,includeInactive=false){const where=includeInactive?"":"WHERE p.active=1";return (await env.DB.prepare(`SELECT p.*,c.name category_name,(SELECT COUNT(*) FROM inventory i WHERE i.product_id=p.id AND i.status='available') stock FROM products p LEFT JOIN categories c ON c.id=p.category_id ${where} ORDER BY p.featured DESC,p.id DESC`).all()).results}
function validateProduct(b){if(!clean(b.name))return "Product name is required.";if(!Number.isFinite(Number(b.price))||Number(b.price)<0)return "Price must be a valid non-negative number.";return null}
async function requireAdmin(req,env){const me=await currentUser(req,env);return me&&me.role==="admin"?me:null}
async function api(req,env,url){
  await ensureAdmin(env);const method=req.method,path=url.pathname,me=await currentUser(req,env);
  if(path==="/api/health")return json({ok:true,version:"4.0.0",logo:LOGO_URL});
  if(path==="/api/me"&&method==="GET")return json({user:me});
  if(path==="/api/categories"&&method==="GET")return json((await env.DB.prepare("SELECT * FROM categories ORDER BY name COLLATE NOCASE").all()).results);
  if(path==="/api/products"&&method==="GET")return json(await productList(env,false));
  if(path==="/api/settings/public"&&method==="GET"){
    const s=await settings(env);return json({instapay_enabled:s.instapay_enabled!=="0",vodafone_cash_enabled:s.vodafone_cash_enabled!=="0",telda_enabled:s.telda_enabled!=="0",whatsapp:s.whatsapp||"",support_text:s.support_text||"",store_name:s.store_name||"Kardivo",store_currency:s.store_currency||"EGP",logo_url:LOGO_URL});
  }
  if(path==="/api/auth/register"&&method==="POST"){
    const b=await req.json();const name=clean(b.name),email=clean(b.email).toLowerCase(),password=String(b.password||"");if(name.length<2||!email.includes("@")||password.length<6)return json({error:"Enter a valid name, email, and password of at least 6 characters."},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"Email already exists."},409);const r=await env.DB.prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,'customer')").bind(name,email,await hash(password)).run();const sid=crypto.randomUUID();await env.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)").bind(sid,r.meta.last_row_id,Date.now()+2592000000).run();return json({user:{id:r.meta.last_row_id,name,email,role:"customer"}},201,{"Set-Cookie":cookie(sid,2592000)})
  }
  if(path==="/api/auth/login"&&method==="POST"){
    const b=await req.json(),email=clean(b.email).toLowerCase();const row=await env.DB.prepare("SELECT id,name,email,role FROM users WHERE email=? AND password_hash=?").bind(email,await hash(String(b.password||""))).first();if(!row)return json({error:"Invalid email or password."},401);const sid=crypto.randomUUID();await env.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,?)").bind(sid,row.id,Date.now()+2592000000).run();return json({user:row},200,{"Set-Cookie":cookie(sid,2592000)})
  }
  if(path==="/api/auth/logout"&&method==="POST"){const raw=req.headers.get("Cookie")||"",match=raw.match(/(?:^|; )kardivo_session=([^;]+)/);if(match)await env.DB.prepare("DELETE FROM sessions WHERE id=?").bind(match[1]).run();return new Response("ok",{headers:{"Set-Cookie":cookie("",0)}})}
  if(path==="/api/orders"&&method==="GET"){if(!me)return json({error:"Login required."},401);const orders=(await env.DB.prepare("SELECT * FROM orders WHERE user_id=? ORDER BY id DESC").bind(me.id).all()).results;return json(orders)}
  if(path==="/api/orders"&&method==="POST"){
    const b=await req.json();if(!Array.isArray(b.items)||!b.items.length)return json({error:"Cart is empty."},400);if(!me&&(!clean(b.guest_name)||!clean(b.guest_contact)))return json({error:"Guest name and contact are required."},400);
    const normalized=b.items.map(x=>({product_id:Number(x.product_id),quantity:Math.max(1,Math.min(99,Number(x.quantity)||1))}));const ids=[...new Set(normalized.map(x=>x.product_id))];const products=ids.length?(await env.DB.prepare(`SELECT * FROM products WHERE active=1 AND id IN (${ids.map(()=>"?").join(",")})`).bind(...ids).all()).results:[];const map=new Map(products.map(p=>[p.id,p]));let subtotal=0;
    for(const item of normalized){const p=map.get(item.product_id);if(!p)return json({error:"One of the products is no longer available."},400);if(p.delivery_type==="code"){const stock=await env.DB.prepare("SELECT COUNT(*) n FROM inventory WHERE product_id=? AND status='available'").bind(p.id).first();if(Number(stock.n)<item.quantity)return json({error:`Not enough stock for ${p.name}.`},400)}subtotal+=Number(p.price)*item.quantity}
    subtotal=money(subtotal);let discount=0;const discountCode=clean(b.discount_code).toUpperCase();if(discountCode){const d=await env.DB.prepare("SELECT * FROM discounts WHERE code=? AND active=1").bind(discountCode).first();if(d&&subtotal>=Number(d.min_order||0)&&(!d.expires_at||new Date(d.expires_at)>new Date()))discount=d.type==="percentage"?subtotal*Number(d.amount)/100:Number(d.amount)}discount=money(Math.min(subtotal,discount));const total=money(subtotal-discount);
    const s=await settings(env),pm=PAYMENT_METHODS.includes(b.payment_method)?b.payment_method:"";if(!pm||s[`${pm}_enabled`]==="0"||!clean(s[pm]))return json({error:"Choose an enabled payment method."},400);
    const orderNumber=`KDV-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const guestName=me?null:clean(b.guest_name),guestContact=me?null:clean(b.guest_contact);const result=await env.DB.prepare("INSERT INTO orders(order_number,user_id,guest_name,guest_contact,subtotal,discount,total,payment_method) VALUES(?,?,?,?,?,?,?,?)").bind(orderNumber,me?.id??null,guestName,guestContact,subtotal,discount,total,pm).run();const orderId=result.meta.last_row_id;
    for(const item of normalized){const p=map.get(item.product_id);await env.DB.prepare("INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price,delivery_type) VALUES(?,?,?,?,?,?)").bind(orderId,p.id,p.name,item.quantity,p.price,p.delivery_type).run()}
    const wa=s.whatsapp?`https://wa.me/${s.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(`Hello Kardivo Support\nOrder: ${orderNumber}\nTotal: ${total.toFixed(2)} EGP\nPayment method: ${pm}`)}`:"";return json({order_number:orderNumber,total,subtotal,discount,payment_method:pm,destination:s[pm],whatsapp:wa,support_text:s.support_text||""},201)
  }
  if(path.startsWith("/api/admin/")){const admin=await requireAdmin(req,env);if(!admin)return json({error:"Admin access required."},403)}
  if(path==="/api/admin/summary"&&method==="GET"){
    const [p,c,o,u,rev,stock]=await Promise.all([env.DB.prepare("SELECT COUNT(*) n FROM products WHERE active=1").first(),env.DB.prepare("SELECT COUNT(*) n FROM categories").first(),env.DB.prepare("SELECT COUNT(*) n FROM orders").first(),env.DB.prepare("SELECT COUNT(*) n FROM users WHERE role='customer'").first(),env.DB.prepare("SELECT COALESCE(SUM(total),0) n FROM orders WHERE payment_status='paid'").first(),env.DB.prepare("SELECT COUNT(*) n FROM inventory WHERE status='available'").first()]);return json({products:p.n,categories:c.n,orders:o.n,customers:u.n,paid_revenue:money(rev.n),available_codes:stock.n})
  }
  if(path==="/api/admin/products"&&method==="GET")return json(await productList(env,true));
  if(path==="/api/admin/products"&&method==="POST"){
    const b=await req.json(),err=validateProduct(b);if(err)return json({error:err},400);const base=slugify(b.slug||b.name);let slug=base;let n=2;while(await env.DB.prepare("SELECT id FROM products WHERE slug=?").bind(slug).first())slug=`${base}-${n++}`;const r=await env.DB.prepare("INSERT INTO products(name,slug,description,price,old_price,image_url,category_id,platform,region,delivery_type,active,featured) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(clean(b.name),slug,clean(b.description),Number(b.price),b.old_price===""||b.old_price==null?null:Number(b.old_price),clean(b.image_url),b.category_id?Number(b.category_id):null,clean(b.platform),clean(b.region),b.delivery_type==="code"?"code":"manual",b.active===false?0:1,b.featured?1:0).run();return json({id:r.meta.last_row_id},201)
  }
  const productMatch=path.match(/^\/api\/admin\/products\/(\d+)$/);if(productMatch&&method==="PUT"){const b=await req.json(),err=validateProduct(b);if(err)return json({error:err},400);const id=Number(productMatch[1]),existing=await env.DB.prepare("SELECT id FROM products WHERE id=?").bind(id).first();if(!existing)return json({error:"Product not found."},404);let newSlug=slugify(b.slug||b.name);const conflict=await env.DB.prepare("SELECT id FROM products WHERE slug=? AND id<>?").bind(newSlug,id).first();if(conflict)newSlug=`${newSlug}-${id}`;await env.DB.prepare("UPDATE products SET name=?,slug=?,description=?,price=?,old_price=?,image_url=?,category_id=?,platform=?,region=?,delivery_type=?,active=?,featured=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(clean(b.name),newSlug,clean(b.description),Number(b.price),b.old_price===""||b.old_price==null?null:Number(b.old_price),clean(b.image_url),b.category_id?Number(b.category_id):null,clean(b.platform),clean(b.region),b.delivery_type==="code"?"code":"manual",b.active?1:0,b.featured?1:0,id).run();return json({ok:true})}if(productMatch&&method==="DELETE"){await env.DB.prepare("UPDATE products SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(Number(productMatch[1])).run();return json({ok:true})}
  if(path==="/api/admin/categories"&&method==="GET")return json((await env.DB.prepare("SELECT * FROM categories ORDER BY id DESC").all()).results);
  if(path==="/api/admin/categories"&&method==="POST"){const b=await req.json();if(!clean(b.name))return json({error:"Category name is required."},400);let s=slugify(b.slug||b.name),base=s,n=2;while(await env.DB.prepare("SELECT id FROM categories WHERE slug=?").bind(s).first())s=`${base}-${n++}`;const r=await env.DB.prepare("INSERT INTO categories(name,slug) VALUES(?,?)").bind(clean(b.name),s).run();return json({id:r.meta.last_row_id},201)}
  const catMatch=path.match(/^\/api\/admin\/categories\/(\d+)$/);if(catMatch&&method==="PUT"){const b=await req.json();if(!clean(b.name))return json({error:"Category name is required."},400);await env.DB.prepare("UPDATE categories SET name=?,slug=? WHERE id=?").bind(clean(b.name),slugify(b.slug||b.name),Number(catMatch[1])).run();return json({ok:true})}if(catMatch&&method==="DELETE"){await env.DB.prepare("UPDATE products SET category_id=NULL WHERE category_id=?").bind(Number(catMatch[1])).run();await env.DB.prepare("DELETE FROM categories WHERE id=?").bind(Number(catMatch[1])).run();return json({ok:true})}
  if(path==="/api/admin/inventory"&&method==="GET")return json((await env.DB.prepare("SELECT i.*,p.name product_name FROM inventory i JOIN products p ON p.id=i.product_id ORDER BY i.id DESC").all()).results);
  if(path==="/api/admin/inventory"&&method==="POST"){const b=await req.json(),productId=Number(b.product_id),codes=[...new Set(String(b.codes||"").split(/\r?\n/).map(clean).filter(Boolean))];if(!productId||!codes.length)return json({error:"Select a product and enter at least one code."},400);let added=0;for(const code of codes){const exists=await env.DB.prepare("SELECT id FROM inventory WHERE product_id=? AND code=?").bind(productId,code).first();if(!exists){await env.DB.prepare("INSERT INTO inventory(product_id,code) VALUES(?,?)").bind(productId,code).run();added++}}return json({count:added},201)}
  const invMatch=path.match(/^\/api\/admin\/inventory\/(\d+)$/);if(invMatch&&method==="DELETE"){await env.DB.prepare("DELETE FROM inventory WHERE id=? AND status='available'").bind(Number(invMatch[1])).run();return json({ok:true})}
  if(path==="/api/admin/discounts"&&method==="GET")return json((await env.DB.prepare("SELECT * FROM discounts ORDER BY id DESC").all()).results);
  if(path==="/api/admin/discounts"&&method==="POST"){const b=await req.json(),code=clean(b.code).toUpperCase();if(!code||!Number.isFinite(Number(b.amount))||Number(b.amount)<0)return json({error:"Enter a valid discount code and amount."},400);await env.DB.prepare("INSERT INTO discounts(code,type,amount,min_order,active,expires_at) VALUES(?,?,?,?,?,?)").bind(code,b.type==="fixed"?"fixed":"percentage",Number(b.amount),Number(b.min_order)||0,b.active===false?0:1,b.expires_at||null).run();return json({ok:true},201)}
  const discMatch=path.match(/^\/api\/admin\/discounts\/(\d+)$/);if(discMatch&&method==="PUT"){const b=await req.json(),code=clean(b.code).toUpperCase();await env.DB.prepare("UPDATE discounts SET code=?,type=?,amount=?,min_order=?,active=?,expires_at=? WHERE id=?").bind(code,b.type==="fixed"?"fixed":"percentage",Number(b.amount)||0,Number(b.min_order)||0,b.active?1:0,b.expires_at||null,Number(discMatch[1])).run();return json({ok:true})}if(discMatch&&method==="DELETE"){await env.DB.prepare("DELETE FROM discounts WHERE id=?").bind(Number(discMatch[1])).run();return json({ok:true})}
  if(path==="/api/admin/orders"&&method==="GET")return json((await env.DB.prepare("SELECT o.*,u.name user_name,u.email user_email,(SELECT GROUP_CONCAT(oi.product_name || ' × ' || oi.quantity, ', ') FROM order_items oi WHERE oi.order_id=o.id) item_summary FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.id DESC").all()).results);
  const orderMatch=path.match(/^\/api\/admin\/orders\/(\d+)$/);if(orderMatch&&method==="GET"){const order=await env.DB.prepare("SELECT o.*,u.name user_name,u.email user_email FROM orders o LEFT JOIN users u ON u.id=o.user_id WHERE o.id=?").bind(Number(orderMatch[1])).first();if(!order)return json({error:"Order not found."},404);const items=(await env.DB.prepare("SELECT * FROM order_items WHERE order_id=? ORDER BY id").bind(order.id).all()).results;const codes=(await env.DB.prepare("SELECT i.*,p.name product_name FROM inventory i JOIN products p ON p.id=i.product_id WHERE i.order_id=?").bind(order.id).all()).results;return json({order,items,codes})}
  if(orderMatch&&method==="PUT"){
    const b=await req.json(),id=Number(orderMatch[1]),payment=["awaiting_payment","paid","failed","refunded"].includes(b.payment_status)?b.payment_status:"awaiting_payment",fulfill=["pending","processing","fulfilled","cancelled"].includes(b.fulfillment_status)?b.fulfillment_status:"pending";await env.DB.prepare("UPDATE orders SET payment_status=?,fulfillment_status=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(payment,fulfill,clean(b.notes),id).run();
    if(payment==="paid"&&fulfill==="fulfilled"){
      const items=(await env.DB.prepare("SELECT * FROM order_items WHERE order_id=? AND delivery_type='code'").bind(id).all()).results;for(const item of items){const existing=await env.DB.prepare("SELECT COUNT(*) n FROM inventory WHERE order_id=? AND product_id=?").bind(id,item.product_id).first();let need=Math.max(0,Number(item.quantity)-Number(existing.n));if(need){const available=(await env.DB.prepare("SELECT id FROM inventory WHERE product_id=? AND status='available' ORDER BY id LIMIT ?").bind(item.product_id,need).all()).results;for(const row of available)await env.DB.prepare("UPDATE inventory SET status='sold',order_id=? WHERE id=? AND status='available'").bind(id,row.id).run()}}}
    return json({ok:true})
  }
  if(path==="/api/admin/settings"&&method==="GET")return json(await settings(env));
  if(path==="/api/admin/settings"&&method==="PUT"){const body=await req.json();for(const [key,value] of Object.entries(body)){if(!/^[a-z0-9_]+$/.test(key))continue;await env.DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(key,String(value??"")).run()}return json({ok:true})}
  return json({error:"Not found"},404)
}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith("/api/")){try{return await api(request,env,url)}catch(error){console.error(error);return json({error:error?.message||"Server error"},500)}}return env.ASSETS.fetch(request)}};
