const J=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json; charset=utf-8",...h}});
const hash=async p=>{const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(p));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")};
const slug=s=>String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||`item-${Date.now()}`;
const cookie=(v,a)=>`kardivo_session=${v}; Path=/; Max-Age=${a}; HttpOnly; Secure; SameSite=Lax`;
async function user(req,e){const c=req.headers.get("Cookie")||"",m=c.match(/kardivo_session=([^;]+)/);if(!m)return null;return await e.DB.prepare("SELECT u.id,u.name,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?").bind(m[1],Date.now()).first()}
async function admin(e){if(!e.ADMIN_EMAIL||!e.ADMIN_PASSWORD)return;const x=await e.DB.prepare("SELECT id FROM users WHERE email=?").bind(e.ADMIN_EMAIL.toLowerCase()).first();if(!x)await e.DB.prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,'admin')").bind("Kardivo Admin",e.ADMIN_EMAIL.toLowerCase(),await hash(e.ADMIN_PASSWORD)).run()}
async function products(e,all=false){return (await e.DB.prepare(`SELECT p.*,c.name category_name,(SELECT COUNT(*) FROM inventory i WHERE i.product_id=p.id AND i.status='available') stock FROM products p LEFT JOIN categories c ON c.id=p.category_id ${all?'':'WHERE p.active=1'} ORDER BY p.featured DESC,p.id DESC`).all()).results}
async function api(req,e,u){
  await admin(e); const m=req.method,p=u.pathname,me=await user(req,e);
  if(p==="/api/me"&&m==="GET")return J({user:me});
  if(p==="/api/categories"&&m==="GET")return J((await e.DB.prepare("SELECT * FROM categories ORDER BY name").all()).results);
  if(p==="/api/products"&&m==="GET")return J(await products(e));
  if(p==="/api/settings/public"&&m==="GET"){const r=(await e.DB.prepare("SELECT key,value FROM settings").all()).results;return J(Object.fromEntries(r.map(x=>[x.key,x.value])))}
  if(p==="/api/auth/register"&&m==="POST"){const b=await req.json();if(!b.name||!b.email||!b.password||b.password.length<6)return J({error:"Invalid registration."},400);const em=b.email.trim().toLowerCase();if(await e.DB.prepare("SELECT id FROM users WHERE email=?").bind(em).first())return J({error:"Email already exists."},409);const r=await e.DB.prepare("INSERT INTO users(name,email,password_hash) VALUES(?,?,?)").bind(b.name.trim(),em,await hash(b.password)).run(),sid=crypto.randomUUID();await e.DB.prepare("INSERT INTO sessions VALUES(?,?,?,CURRENT_TIMESTAMP)").bind(sid,r.meta.last_row_id,Date.now()+2592e6).run();return J({user:{id:r.meta.last_row_id,name:b.name,email:em,role:"customer"}},201,{"Set-Cookie":cookie(sid,2592000)})}
  if(p==="/api/auth/login"&&m==="POST"){const b=await req.json(),em=String(b.email||"").trim().toLowerCase(),x=await e.DB.prepare("SELECT id,name,email,role FROM users WHERE email=? AND password_hash=?").bind(em,await hash(String(b.password||""))).first();if(!x)return J({error:"Invalid email or password."},401);const sid=crypto.randomUUID();await e.DB.prepare("INSERT INTO sessions VALUES(?,?,?,CURRENT_TIMESTAMP)").bind(sid,x.id,Date.now()+2592e6).run();return J({user:x},200,{"Set-Cookie":cookie(sid,2592000)})}
  if(p==="/api/auth/logout"&&m==="POST"){const c=req.headers.get("Cookie")||"",x=c.match(/kardivo_session=([^;]+)/);if(x)await e.DB.prepare("DELETE FROM sessions WHERE id=?").bind(x[1]).run();return new Response("ok",{headers:{"Set-Cookie":cookie("",0)}})}
  if(p==="/api/orders"&&m==="GET"){if(!me)return J({error:"Login required."},401);return J((await e.DB.prepare("SELECT * FROM orders WHERE user_id=? ORDER BY id DESC").bind(me.id).all()).results)}
  if(p==="/api/orders"&&m==="POST"){
    const b=await req.json(); if(!b.items?.length)return J({error:"Cart is empty."},400);
    if(!me && (!b.guest_name||!b.guest_contact))return J({error:"Guest name and contact are required."},400);
    const ids=b.items.map(x=>Number(x.product_id)),ps=(await e.DB.prepare(`SELECT * FROM products WHERE active=1 AND id IN (${ids.map(()=>'?').join(',')})`).bind(...ids).all()).results,map=new Map(ps.map(x=>[x.id,x]));let sub=0;
    for(const x of b.items){const p2=map.get(Number(x.product_id)),q=Math.max(1,Number(x.quantity)||1);if(!p2)return J({error:"Product unavailable."},400);if(p2.delivery_type==="code"){const st=await e.DB.prepare("SELECT COUNT(*) n FROM inventory WHERE product_id=? AND status='available'").bind(p2.id).first();if(st.n<q)return J({error:`Not enough stock for ${p2.name}.`},400)}sub+=p2.price*q}
    let dis=0;if(b.discount_code){const d=await e.DB.prepare("SELECT * FROM discounts WHERE code=? AND active=1").bind(String(b.discount_code).trim().toUpperCase()).first();if(d&&sub>=d.min_order&&(!d.expires_at||new Date(d.expires_at)>new Date()))dis=d.type==='percentage'?sub*d.amount/100:d.amount}
    const total=Math.max(0,Math.round((sub-dis)*100)/100),pm=["instapay","vodafone_cash","telda"].includes(b.payment_method)?b.payment_method:null;const settings=Object.fromEntries((await e.DB.prepare("SELECT key,value FROM settings").all()).results.map(x=>[x.key,x.value]));if(!pm||settings[pm+'_enabled']==='0'||!settings[pm])return J({error:"Choose an available payment method."},400);
    const num=`KDV-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`;
    const r=await e.DB.prepare("INSERT INTO orders(order_number,user_id,guest_name,guest_contact,subtotal,discount,total,payment_method) VALUES(?,?,?,?,?,?,?,?)").bind(num,me?.id??null,me?null:String(b.guest_name).trim(),me?null:String(b.guest_contact).trim(),sub,dis,total,pm).run();
    for(const x of b.items){const p2=map.get(Number(x.product_id));await e.DB.prepare("INSERT INTO order_items(order_id,product_id,product_name,quantity,unit_price,delivery_type) VALUES(?,?,?,?,?,?)").bind(r.meta.last_row_id,p2.id,p2.name,Math.max(1,Number(x.quantity)||1),p2.price,p2.delivery_type).run()}
    const ss=settings,wa=ss.whatsapp?`https://wa.me/${ss.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(`Hello Kardivo Support\nOrder: ${num}\nTotal: ${total.toFixed(2)} EGP\nPayment method: ${pm}`)}`:"";
    return J({order_number:num,total,payment_method:pm,destination:ss[pm]||"",whatsapp:wa,support_text:ss.support_text||""},201)
  }
  if(p.startsWith("/api/admin/")&&(!me||me.role!=="admin"))return J({error:"Admin access required."},403);
  if(p==="/api/admin/products"&&m==="GET")return J(await products(e,true));
  if(p==="/api/admin/products"&&m==="POST"){const b=await req.json(),r=await e.DB.prepare("INSERT INTO products(name,slug,description,price,old_price,image_url,category_id,platform,region,delivery_type,active,featured) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(b.name,slug(b.slug||b.name),b.description||"",Number(b.price)||0,b.old_price?Number(b.old_price):null,b.image_url||"",b.category_id?Number(b.category_id):null,b.platform||"",b.region||"",b.delivery_type==="code"?"code":"manual",b.active===false?0:1,b.featured?1:0).run();return J({id:r.meta.last_row_id},201)}
  const pmatch=p.match(/^\/api\/admin\/products\/(\d+)$/);if(pmatch&&m==="PUT"){const b=await req.json();await e.DB.prepare("UPDATE products SET name=?,slug=?,description=?,price=?,old_price=?,image_url=?,category_id=?,platform=?,region=?,delivery_type=?,active=?,featured=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.name,slug(b.slug||b.name),b.description||"",Number(b.price)||0,b.old_price?Number(b.old_price):null,b.image_url||"",b.category_id?Number(b.category_id):null,b.platform||"",b.region||"",b.delivery_type==="code"?"code":"manual",b.active?1:0,b.featured?1:0,pmatch[1]).run();return J({ok:true})}if(pmatch&&m==="DELETE"){await e.DB.prepare("UPDATE products SET active=0 WHERE id=?").bind(pmatch[1]).run();return J({ok:true})}
  if(p==="/api/admin/categories"&&m==="POST"){const b=await req.json();if(!b.name)return J({error:"Category name required."},400);const r=await e.DB.prepare("INSERT INTO categories(name,slug) VALUES(?,?)").bind(b.name.trim(),slug(b.slug||b.name)).run();return J({id:r.meta.last_row_id},201)}
  if(p==="/api/admin/orders"&&m==="GET")return J((await e.DB.prepare("SELECT o.*,u.name user_name,u.email user_email FROM orders o LEFT JOIN users u ON u.id=o.user_id ORDER BY o.id DESC").all()).results);
  const om=p.match(/^\/api\/admin\/orders\/(\d+)$/);if(om&&m==="PUT"){const b=await req.json();await e.DB.prepare("UPDATE orders SET payment_status=?,fulfillment_status=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.payment_status,b.fulfillment_status,b.notes||"",om[1]).run();return J({ok:true})}
  if(p==="/api/admin/discounts"&&m==="GET")return J((await e.DB.prepare("SELECT * FROM discounts ORDER BY id DESC").all()).results);
  if(p==="/api/admin/discounts"&&m==="POST"){const b=await req.json();await e.DB.prepare("INSERT INTO discounts(code,type,amount,min_order,active,expires_at) VALUES(?,?,?,?,?,?)").bind(String(b.code).toUpperCase(),b.type,Number(b.amount),Number(b.min_order)||0,1,b.expires_at||null).run();return J({ok:true},201)}
  if(p==="/api/admin/inventory"&&m==="GET")return J((await e.DB.prepare("SELECT i.*,p.name product_name FROM inventory i JOIN products p ON p.id=i.product_id ORDER BY i.id DESC").all()).results);
  if(p==="/api/admin/inventory"&&m==="POST"){const b=await req.json();let n=0;for(const code of String(b.codes||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){await e.DB.prepare("INSERT INTO inventory(product_id,code) VALUES(?,?)").bind(Number(b.product_id),code).run();n++}return J({count:n},201)}
  if(p==="/api/admin/settings"&&m==="GET")return J(Object.fromEntries((await e.DB.prepare("SELECT key,value FROM settings").all()).results.map(x=>[x.key,x.value])));
  if(p==="/api/admin/settings"&&m==="PUT"){for(const [k,v] of Object.entries(await req.json()))await e.DB.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(k,String(v??"")).run();return J({ok:true})}
  return J({error:"Not found"},404)
}
export default{async fetch(req,e){const u=new URL(req.url);if(u.pathname.startsWith('/api/')){try{return await api(req,e,u)}catch(err){console.error(err);return J({error:err.message||"Server error"},500)}}return e.ASSETS.fetch(req)}};
