name = "kardivo"
main = "worker.js"
compatibility_date = "2026-10-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "kardivo-db"
database_id = "3c955451-b6fe-459e-95dd-b90bad198625"
